import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUiRole } from '@/lib/server/current-profile';
import { getEvolutionConnectionState } from '@/lib/server/evolution-guard';
import { evolutionConfigured, getEvolutionConfig } from '@/lib/server/evolution';
import { consumeRateLimit, getServiceClient, requestComesFromSameSite } from '@/lib/server/security';

export const runtime='nodejs'; export const dynamic='force-dynamic'; export const maxDuration=60;
const SLUG='seminario-apocalipse-2026'; const TEST_PHONE='5551995092781'; const MAX_PDF_BYTES=8*1024*1024; const BATCH_SIZE=5; const FILE_NAME='O FIM PERTENCE A CRISTO.pdf';
type Recipient={id:string;name:string;phone:string;material:'PDF'|'Física'};
function txt(v:unknown){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function material(v:unknown):'PDF'|'Física'|''{const s=txt(v);if(s.includes('pdf')||s.includes('digital'))return'PDF';if(s.includes('fisic'))return'Física';return''}
function pay(a:Record<string,unknown>){const p=a.__payment;return p&&typeof p==='object'&&!Array.isArray(p)?String((p as Record<string,unknown>).status||''):''}
function phone(v:unknown){let d=String(v??'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.length===10||d.length===11)d=`55${d}`;return d}
function valid(v:unknown){const d=phone(v);const n=d.startsWith('55')?d.slice(2):'';return n.length===11&&Number(n.slice(0,2))>=11&&Number(n.slice(0,2))<=99&&n.slice(2).startsWith('9')}
function envelope(payload:unknown){const d=(payload||{}) as Record<string,unknown>;const r=d.response&&typeof d.response==='object'?d.response as Record<string,unknown>:d;const m=r.message&&typeof r.message==='object'?r.message as Record<string,unknown>:null;const k=(r.key&&typeof r.key==='object'?r.key:m?.key&&typeof m.key==='object'?m.key:null) as Record<string,unknown>|null;return{id:String(k?.id||''),remoteJid:String(k?.remoteJid||''),status:String(r.status||m?.status||d.status||'UNKNOWN').toUpperCase()}}
function allowedJids(p:string){const s=new Set([`${p}@s.whatsapp.net`]);if(p.length===13&&p.startsWith('55')&&p.charAt(4)==='9')s.add(`${p.slice(0,4)}${p.slice(5)}@s.whatsapp.net`);return s}
async function send(media:string,r:Recipient,index:number,total:number){const c=getEvolutionConfig();const response=await fetch(`${c.apiUrl}/message/sendMedia/${encodeURIComponent(c.instance)}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:c.apiKey},body:JSON.stringify({number:TEST_PHONE,mediatype:'document',mimetype:'application/pdf',caption:`🧪 TESTE ESPELHO ${index}/${total}\nDestinatário real: ${r.name}\nMaterial escolhido: ${r.material}\nWhatsApp cadastrado: ${r.phone}\n\nOlá! Segue a apostila digital do Seminário O Fim Pertence a Cristo. 🙏`,media,fileName:FILE_NAME,delay:1800}),cache:'no-store',signal:AbortSignal.timeout(20000)});const raw=await response.text();let payload:unknown={};try{payload=JSON.parse(raw)}catch{}const e=envelope(payload);return response.ok&&!!e.id&&(!e.remoteJid||allowedJids(TEST_PHONE).has(e.remoteJid))&&!['ERROR','FAILED','CANCELED','CANCELLED'].includes(e.status)}

export async function POST(request:NextRequest){
 if(!requestComesFromSameSite(request))return NextResponse.json({error:'Origem da solicitação não autorizada.'},{status:403}); if(await getCurrentUiRole()!=='admin')return NextResponse.json({error:'Acesso restrito ao administrador.'},{status:403});
 if(!await consumeRateLimit(request,'seminar_pdf_bulk_mirror_test',60,12))return NextResponse.json({error:'Aguarde um pouco antes do próximo lote.'},{status:429});
 const connection=await getEvolutionConnectionState();if(!connection.open)return NextResponse.json({error:'O WhatsApp da CEAMI não está conectado.'},{status:409});const c=getEvolutionConfig();if(!evolutionConfigured(c))return NextResponse.json({error:'Evolution API não configurada.'},{status:503});
 const fd=await request.formData();const file=fd.get('file');const start=Math.max(0,Number(fd.get('start')||0)||0);if(!(file instanceof File)||file.type!=='application/pdf')return NextResponse.json({error:'Selecione o PDF do seminário.'},{status:400});if(file.size<=0||file.size>MAX_PDF_BYTES)return NextResponse.json({error:'O PDF deve ter no máximo 8 MB.'},{status:400});
 const service=getServiceClient();if(!service)return NextResponse.json({error:'Serviço temporariamente indisponível.'},{status:503});const{data:form}=await service.from('forms').select('id').eq('slug',SLUG).maybeSingle();if(!form)return NextResponse.json({error:'Formulário não encontrado.'},{status:404});const{data,error}=await service.from('form_submissions').select('id, respondent_name, respondent_phone, answers, created_at').eq('form_id',form.id).order('created_at',{ascending:true});if(error)return NextResponse.json({error:'Não foi possível carregar as inscrições.'},{status:500});
 const recipients:Recipient[]=[];const blocked:string[]=[];for(const row of data||[]){const a=row.answers&&typeof row.answers==='object'&&!Array.isArray(row.answers)?row.answers as Record<string,unknown>:{};const m=material(a.apostila);if(pay(a)!=='paid'||!m)continue;const raw=row.respondent_phone||a.telefone||a.whatsapp||a.celular||'';const name=String(row.respondent_name||a.nome_completo||'Não informado');if(!valid(raw)){blocked.push(name);continue}recipients.push({id:row.id,name,phone:phone(raw),material:m})}
 if(blocked.length)return NextResponse.json({error:`Existem ${blocked.length} número(s) para revisar antes do teste geral.`,blocked},{status:409});if(start>=recipients.length)return NextResponse.json({ok:true,sent:0,total:recipients.length,start,nextStart:recipients.length,done:true,destination:'(51) 99509-2781'});
 const batch=recipients.slice(start,start+BATCH_SIZE);const media=Buffer.from(await file.arrayBuffer()).toString('base64');let sent=0;const failed:string[]=[];for(let i=0;i<batch.length;i++){try{if(await send(media,batch[i],start+i+1,recipients.length))sent++;else failed.push(batch[i].name)}catch{failed.push(batch[i].name)}}const nextStart=start+batch.length;const body={ok:failed.length===0,sent,batchSize:batch.length,total:recipients.length,start,nextStart,done:nextStart>=recipients.length,failed,destination:'(51) 99509-2781',range:`${start+1}-${nextStart}`};return NextResponse.json(body,{status:failed.length?502:200,headers:{'Cache-Control':'no-store'}});
}
