'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Setting={enabled:boolean;send_time:string;test_mode:boolean;test_member_id:string|null;group_id:string;last_sent_at:string|null;last_status:string|null;last_error:string|null};
type Member={id:string;full_name:string;phone:string|null};

export default function Page(){
 const supabase=useMemo(()=>createClient(),[]);
 const[setting,setSetting]=useState<Setting|null>(null);const[members,setMembers]=useState<Member[]>([]);const[msg,setMsg]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){const[{data:s},{data:m}]=await Promise.all([supabase.from('birthday_automation_settings').select('*').eq('id','default').maybeSingle(),supabase.from('members').select('id,full_name,phone').not('phone','is',null).order('full_name')]);setSetting(s as Setting);setMembers((m||[]) as Member[])}
 async function save(){if(!setting)return;const{error}=await supabase.from('birthday_automation_settings').update({enabled:setting.enabled,send_time:setting.send_time,test_mode:setting.test_mode,test_member_id:setting.test_mode?setting.test_member_id:null,last_sent_date:null,updated_at:new Date().toISOString()}).eq('id','default');setMsg(error?error.message:'Configuração salva com sucesso.')}
 if(!setting)return <main className="auto"><section><h1>Automação não instalada</h1><p>Execute as migrations no Supabase.</p></section><Style/></main>;
 return <main className="auto"><section><header><div><small>CEAMI MEMBROS</small><h1>Automação de aniversários</h1><p>O Supabase verifica o horário uma vez por minuto.</p></div><Link href="/">Voltar</Link></header><label className="check"><input type="checkbox" checked={setting.enabled} onChange={e=>setSetting({...setting,enabled:e.target.checked})}/> Automação ativada</label><label>Horário diário<input type="time" value={setting.send_time.slice(0,5)} onChange={e=>setSetting({...setting,send_time:e.target.value})}/></label><label>Modo<select value={setting.test_mode?'test':'official'} onChange={e=>setSetting({...setting,test_mode:e.target.value==='test'})}><option value="test">Teste automático</option><option value="official">Aniversariantes reais</option></select></label>{setting.test_mode&&<label>Membro simulado<select value={setting.test_member_id||''} onChange={e=>setSetting({...setting,test_member_id:e.target.value||null})}><option value="">Selecione</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name} — {m.phone}</option>)}</select></label>}<div className="info"><b>Grupo:</b> {setting.group_id}<br/><b>Última execução:</b> {setting.last_sent_at?new Date(setting.last_sent_at).toLocaleString('pt-BR'):'Ainda não executada'}<br/><b>Status:</b> {setting.last_status||'—'}{setting.last_error&&<><br/><b>Erro:</b> {setting.last_error}</>}</div>{msg&&<p className="msg">{msg}</p>}<footer><Link href="/teste-aniversario">Teste manual</Link><button onClick={()=>void save()}>Salvar automação</button></footer></section><Style/></main>}
function Style(){return <style jsx global>{`.auto{min-height:100vh;background:#f3f6f7;color:#173746;padding:28px 16px}.auto>section{width:min(760px,100%);margin:auto;background:#fff;border:1px solid #dfe7ea;border-radius:22px;padding:26px;display:grid;gap:18px}.auto header{display:flex;justify-content:space-between;gap:18px}.auto h1{margin:4px 0}.auto p{color:#71838c}.auto small{color:#df6034;font-weight:900;letter-spacing:.12em}.auto a{color:#173746;font-weight:800;text-decoration:none}.auto label{display:grid;gap:7px;font-weight:800}.auto input,.auto select{height:50px;border:1px solid #d7e1e5;border-radius:13px;padding:0 13px;background:#fff}.auto .check{display:flex;align-items:center;gap:10px}.auto .check input{width:22px;height:22px}.info{background:#f6f8f9;padding:15px;border-radius:14px;line-height:1.7}.msg{background:#eaf7f0;color:#26734c;padding:12px;border-radius:12px;font-weight:800}.auto footer{display:flex;justify-content:flex-end;gap:10px}.auto footer a,.auto button{padding:13px 17px;border-radius:12px}.auto footer a{background:#e8eef0}.auto button{border:0;background:#df6034;color:#fff;font-weight:900}@media(max-width:600px){.auto header{display:grid}.auto footer{display:grid;grid-template-columns:1fr 1fr}.auto footer a,.auto footer button{text-align:center}}`}</style>}
