'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { SEMINAR_APOCALIPSE_SLUG } from '@/lib/seminar-apocalipse';

type Recipient={id:string;name:string;originalPhone:string;normalizedPhone:string;status:'confirmed'|'warning'|'invalid';reason:string;material:string};
type Payload={error?:string;summary?:{total:number;confirmed:number;warnings:number;invalid:number;ready:boolean};recipients?:Recipient[]};
function fmt(v:string){const d=v.replace(/\D/g,'');const n=d.startsWith('55')?d.slice(2):d;if(n.length===11)return`(${n.slice(0,2)}) ${n.slice(2,7)}-${n.slice(7)}`;if(n.length===10)return`(${n.slice(0,2)}) ${n.slice(2,6)}-${n.slice(6)}`;return v||'—'}
function wait(ms:number){return new Promise(resolve=>window.setTimeout(resolve,ms))}

export default function SeminarPendingPaymentSender(){
 const supabase=useMemo(()=>createClient(),[]);const[active,setActive]=useState(false);const[loading,setLoading]=useState(false);const[sending,setSending]=useState(false);const[data,setData]=useState<Payload|null>(null);const[reviewOnly,setReviewOnly]=useState(false);const[sentIds,setSentIds]=useState<string[]>([]);const[notice,setNotice]=useState('');const[progress,setProgress]=useState('');
 useEffect(()=>{let stop=false;let timer:number|null=null;let busy=false;async function detect(){if(stop||busy)return;const id=document.querySelector<HTMLElement>('.forms-responses')?.dataset.formId||'';if(!id){setActive(false);return}busy=true;try{const{data:f}=await supabase.from('forms').select('slug').eq('id',id).maybeSingle();if(!stop)setActive(f?.slug===SEMINAR_APOCALIPSE_SLUG)}finally{busy=false}}function schedule(){if(timer)clearTimeout(timer);timer=window.setTimeout(()=>void detect(),120)}schedule();const o=new MutationObserver(schedule);o.observe(document.body,{childList:true,subtree:true});return()=>{stop=true;if(timer)clearTimeout(timer);o.disconnect()}},[supabase]);
 if(!active)return null;
 async function review(){setLoading(true);setNotice('');setProgress('');try{const r=await fetch('/api/admin/forms/seminar-apocalipse/pending-preflight',{cache:'no-store'});const p=await r.json().catch(()=>({})) as Payload;if(!r.ok){setNotice(p.error||'Não foi possível revisar os pendentes.');return}setData(p);setSentIds([]);setReviewOnly(((p.summary?.warnings||0)+(p.summary?.invalid||0))>0)}finally{setLoading(false)}}
 async function sendAll(){const recipients=data?.recipients||[];const summary=data?.summary;if(!summary?.ready)return;const eligible=recipients.filter(x=>x.status==='confirmed'&&!sentIds.includes(x.id));if(!eligible.length){setNotice('Todos os pendentes revisados já receberam a cobrança.');return}const batches=Math.ceil(eligible.length/5);if(!window.confirm(`Enviar cobrança agora para ${eligible.length} pessoa(s)?\n\nO sistema enviará automaticamente em ${batches} lote(s) de até 5, com pausa entre os lotes.`))return;setSending(true);setNotice('');setProgress('Iniciando cobranças...');let sentTotal=0;let completedIds=[...sentIds];try{for(let offset=0;offset<eligible.length;offset+=5){const batch=eligible.slice(offset,offset+5);const currentBatch=Math.floor(offset/5)+1;setProgress(`Enviando lote ${currentBatch}/${batches} · ${batch.map(x=>x.name).join(', ')}`);const r=await fetch('/api/admin/forms/seminar-apocalipse/send-pending-reminder-batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:batch.map(x=>x.id)})});const p=await r.json().catch(()=>({})) as {error?:string;sent?:number;sentIds?:string[];skipped?:unknown[];failed?:string[]};if(!r.ok){setNotice(p.error||`O lote ${currentBatch} não foi concluído.`);setProgress(`Parado no lote ${currentBatch}/${batches}. Os lotes anteriores foram preservados.`);return}const confirmedIds=Array.isArray(p.sentIds)?p.sentIds:batch.slice(0,p.sent||0).map(x=>x.id);completedIds=[...new Set([...completedIds,...confirmedIds])];setSentIds(completedIds);sentTotal+=p.sent||0;setProgress(`Lote ${currentBatch}/${batches} concluído · ${sentTotal} cobrança(s) enviada(s).`);if(offset+5<eligible.length)await wait(6000)}setNotice(`Concluído: ${sentTotal} cobrança(s) enviada(s) automaticamente em lotes de até 5.`);setProgress('Envio concluído.')}finally{setSending(false)}}
 const s=data?.summary;const all=data?.recipients||[];const reviewCount=(s?.warnings||0)+(s?.invalid||0);const visible=reviewOnly?all.filter(x=>x.status!=='confirmed'):all;const remaining=all.filter(x=>x.status==='confirmed'&&!sentIds.includes(x.id)).length;
 return <section className="ceami-pending-box"><div className="ceami-pending-head"><div><strong>Cobrança de pagamentos pendentes</strong><span>Revise os números antes de enviar. Depois o sistema dispara automaticamente em lotes de até 5.</span></div><div className="ceami-pending-actions"><button className="secondary" onClick={()=>void review()} disabled={loading||sending}>{loading?'Revisando...':'Revisar pendentes'}</button><button onClick={()=>void sendAll()} disabled={sending||!s?.ready||remaining===0}>{sending?'Enviando automaticamente...':`Enviar cobranças${s?.ready?` (${remaining})`:''}`}</button></div></div>
 {s&&<><div className={s.ready?'pending-status ok':'pending-status review'}><strong>{s.total} pendentes</strong><span>{s.ready?'✓ Lista pronta para cobrança':`⚠ ${reviewCount} número(s) para revisar`}</span></div>{reviewCount>0&&<div className="pending-filters"><button className={!reviewOnly?'active':''} onClick={()=>setReviewOnly(false)}>Todos ({s.total})</button><button className={reviewOnly?'active warn':''} onClick={()=>setReviewOnly(true)}>Só revisar ({reviewCount})</button></div>}<div className="pending-table-wrap"><table><thead><tr><th>Nome</th><th>WhatsApp</th><th>Material</th><th>Status</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{fmt(x.normalizedPhone||x.originalPhone)}</td><td>{x.material}</td><td><span className={`badge ${x.status==='confirmed'?'ok':'review'}`}>{sentIds.includes(x.id)?'✓ Cobrança enviada':x.status==='confirmed'?'✓ OK':'⚠ Revisar'}</span>{x.status!=='confirmed'&&<small>{x.reason}</small>}</td></tr>)}</tbody></table></div></>}{progress&&<p className="progress">{progress}</p>}{notice&&<p>{notice}</p>}
 <style>{`.ceami-pending-box{margin:12px 0 0;padding:14px 15px;border:1px solid #ead8c2;border-radius:14px;background:#fff8ef;display:grid;gap:10px}.ceami-pending-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.ceami-pending-head>div:first-child{display:grid;gap:3px}.ceami-pending-box strong{color:#5b3d1e;font-size:13px}.ceami-pending-box span{font-size:11px;color:#786a5d}.ceami-pending-actions{display:flex;gap:8px;flex-wrap:wrap}.ceami-pending-box button{border:0;border-radius:10px;background:#8a551f;color:white;font-weight:900;padding:10px 12px}.ceami-pending-box button.secondary{background:white;color:#70491f;border:1px solid #d7bf9e}.ceami-pending-box button:disabled{opacity:.45}.pending-status{display:flex;justify-content:space-between;gap:8px;padding:10px 12px;border-radius:10px}.pending-status.ok{background:#edf8ef}.pending-status.review{background:#fff1df}.pending-status.ok span{color:#2f6f3d}.pending-status.review span{color:#9a5d16}.pending-filters{display:flex;gap:7px}.pending-filters button{background:white;color:#6b5a49;border:1px solid #dacbb6;padding:7px 10px;font-size:11px}.pending-filters button.active{background:#64431f;color:white}.pending-filters button.active.warn{background:#a15f14}.pending-table-wrap{overflow:auto;border:1px solid #eadfce;border-radius:12px;background:white}.pending-table-wrap table{width:100%;border-collapse:collapse;min-width:620px}.pending-table-wrap th,.pending-table-wrap td{padding:9px 10px;border-bottom:1px solid #eee5d9;text-align:left;font-size:12px;vertical-align:top}.pending-table-wrap th{background:#faf4ec;font-size:11px;color:#5f5144}.pending-table-wrap small{display:block;margin-top:4px;color:#7e7369}.badge{display:inline-flex!important;padding:4px 7px;border-radius:999px;font-weight:900!important}.badge.ok{background:#edf8ef;color:#2f6f3d!important}.badge.review{background:#fff7df;color:#8a6414!important}.ceami-pending-box p{margin:0;background:#f6efe5;padding:8px 10px;border-radius:9px;font-size:12px;font-weight:800;color:#604b36}.ceami-pending-box p.progress{background:#eef5fb;color:#31566f}@media(max-width:700px){.ceami-pending-head{display:grid}.ceami-pending-actions{display:grid;grid-template-columns:1fr 1fr;position:sticky;top:10px;z-index:17;padding:8px;background:rgba(255,248,239,.96);border:1px solid #ead8c2;border-radius:12px;box-shadow:0 6px 18px rgba(60,42,20,.12);backdrop-filter:blur(8px)}.ceami-pending-actions button{width:100%;font-size:11px;padding:9px 7px}.pending-status{flex-direction:column;align-items:flex-start}.pending-filters{display:grid;grid-template-columns:1fr 1fr}.pending-filters button{width:100%}}`}</style></section>
}
