import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUiRole } from '@/lib/server/current-profile';
import { getEvolutionConnectionState } from '@/lib/server/evolution-guard';
import { evolutionConfigured, getEvolutionConfig } from '@/lib/server/evolution';
import { consumeRateLimit, getServiceClient, requestComesFromSameSite } from '@/lib/server/security';

export const runtime='nodejs'; export const dynamic='force-dynamic'; export const maxDuration=60;
const SLUG='seminario-apocalipse-2026'; const MAX_BATCH=5; const MAX_PDF_BYTES=8*1024*1024; const FILE_NAME='O FIM PERTENCE A CRISTO.pdf';
function txt(v:unknown){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function material(v:unknown){const s=txt(v);if(s.includes('pdf')||s.includes('digital'))return'PDF';if(s.includes('fisic'))return'Física';return''}
function pay(a:Record<string,unknown>){const p=a.__payment;return p&&typeof p==='object'&&!Array.isArray(p)?String((p as Record<string,unknown>).status||''):''}
function delivered(a:Record<string,unknown>){const d=a.__seminar_pdf_delivery;return !!d&&typeof d==='object'&&!Array.isArray(d)&&String((d as Record<string,unknown>).status||'')==='sent'}
function phone(v:unknown){let d=String(v??'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('0')&&d.length>11)d=d.replace(/^0+/,'');if(d.length===10||d.length===11)d=`55${d}`;return d}
function valid(v:unknown){const d=phone(v);const n=d.startsWith('55')?d.slice(2):'';return n.length===11&&Number(n.slice(0,2))>=11&&Number(n.slice(0,2))<=99&&n.slice(2).startsWith('9')}
function env(payload:unknown){const d=(payload||{}) as Record<string,unknown>;const r=d.response&&typeof d.response==='object'?d.response as Record<string,unknown>:d;const m=r.message&&typeof r.message==='object'?r.message as Record<string,unknown>:null;const k=(r.key&&typeof r.key==='object'?r.key:m?.key&&typeof m.key==='object'?m.key:null) as Record<string,unknown>|null;return{id:String(k?.id||''),remoteJid:String(k?.remoteJid||''),status:String(r.status||m?.status||d.status||'UNKNOWN').toUpperCase()}}
function accepted(p:string,jid:string){if(!jid)return true;if(jid===`${p}@s.whatsapp.net`)return true;return p.length===13&&p.startsWith('55')&&p.charAt(4)==='9'&&jid===`${p.slice(0,4)}${p.slice(5)}@s.whatsapp.net`}
async function send(number:string,media:string){const c=getEvolutionConfig();const response=await fetch(`${c.apiUrl}/message/sendMedia/${encodeURIComponent(c.instance)}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:c.apiKey},body:JSON.stringify({number,mediatype:'document',mimetype:'application/pdf',caption:'Olá! Segue a apostila digital do Seminário O Fim Pertence a Cristo. 🙏',media,fileName:FILE_NAME,delay:1800}),cache:'no-store',signal:AbortSignal.timeout(20000)});const raw=await response.text();let payload:unknown={};try{payload=JSON.parse(raw)}catch{}const e=env(payload);const ok=response.ok&&!!e.id&&accepted(number,e.remoteJid)&&!['ERROR','FAILED','CANCELED','CANCELLED'].includes(e.status);return{ok,id:e.id,status:e.status}}

export async function POST(request:NextRequest){
 if(!requestComesFromSameSite(request))return NextResponse.json({error:'Origem não autorizada.'},{status:403});if(await getCurrentUiRole()!=='admin')return NextResponse.json({error:'Acesso restrito ao administrador.'},{status:403});if(!await consumeRateLimit(request,'seminar_pdf_real_batch',60,12))return NextResponse.json({error:'Aguarde um pouco antes do próximo lote.'},{status:429});
 const connection=await getEvolutionConnectionState();if(!connection.open)return NextResponse.json({error:'O WhatsApp da CEAMI não está conectado.'},{status:409});const c=getEvolutionConfig();if(!evolutionConfigured(c))return NextResponse.json({error:'Evolution API não configurada.'},{status:503});
 const fd=await request.formData();const file=fd.get('file');if(!(file instanceof File)||file.type!=='application/pdf')return NextResponse.json({error:'Selecione o PDF do seminário.'},{status:400});if(file.size<=0||file.size>MAX_PDF_BYTES)return NextResponse.json({error:'O PDF deve ter no máximo 8 MB.'},{status:400});
 const service=getServiceClient();if(!service)return NextResponse.json({error:'Serviço temporariamente indisponível.'},{status:503});const{data:form}=await service.from('forms').select('id').eq('slug',SLUG).maybeSingle();if(!form)return NextResponse.json({error:'Formulário não encontrado.'},{status:404});
 const{data,error}=await service.from('form_submissions').select('id, respondent_name, respondent_phone, answers, created_at').eq('form_id',form.id).order('created_at',{ascending:true});if(error)return NextResponse.json({error:'Não foi possível carregar as inscrições.'},{status:500});
 const eligible=(data||[]).filter(row=>{const a=row.answers&&typeof row.answers==='object'&&!Array.isArray(row.answers)?row.answers as Record<string,unknown>:{};return pay(a)==='paid'&&!!material(a.apostila)&&!delivered(a)});
 const batch=eligible.slice(0,MAX_BATCH);if(!batch.length)return NextResponse.json({ok:true,sent:0,remaining:0,done:true,sentIds:[]});
 const media=Buffer.from(await file.arrayBuffer()).toString('base64');const sentIds:string[]=[];const failed:string[]=[];const skipped:string[]=[];
 for(const row of batch){const a=row.answers&&typeof row.answers==='object'&&!Array.isArray(row.answers)?row.answers as Record<string,unknown>:{};const number=phone(row.respondent_phone||a.telefone||a.whatsapp||a.celular||'');if(!valid(number)){skipped.push(String(row.id));continue}try{const result=await send(number,media);if(!result.ok){failed.push(String(row.id));continue}const nextAnswers={...a,__seminar_pdf_delivery:{status:'sent',sent_at:new Date().toISOString(),phone:number,message_id:result.id,provider_status:result.status}};const{error:updateError}=await service.from('form_submissions').update({answers:nextAnswers}).eq('id',row.id);if(updateError){failed.push(String(row.id));continue}sentIds.push(String(row.id))}catch{failed.push(String(row.id))}}
 const remaining=Math.max(0,eligible.length-sentIds.length-skipped.length);return NextResponse.json({ok:failed.length===0,sent:sentIds.length,sentIds,failed,skipped,remaining,done:remaining===0&&failed.length===0},{status:failed.length?502:200,headers:{'Cache-Control':'no-store'}})
}
