'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

export default function Page(){
 const[origin,setOrigin]=useState('https://ceami-membros.vercel.app');
 useEffect(()=>setOrigin(window.location.origin),[]);
 const consultUrl=`${origin}/consultar`;
 const integraUrl=`${origin}/integra`;
 const qr=(value:string)=>`https://api.qrserver.com/v1/create-qr-code/?size=260x260&margin=12&data=${encodeURIComponent(value)}`;
 return <main className="materials"><section><header><div><small>CEAMI MEMBROS</small><h1>Domínio e QR Codes</h1><p>Materiais para divulgar a consulta e o novo cadastro.</p></div><Link href="/ajustes-aniversario">Voltar aos ajustes</Link></header><div className="domain"><b>Domínio recomendado</b><code>membros.ceamirs.com.br</code><p>Na Vercel, adicione esse domínio ao projeto e crie no provedor de DNS o registro indicado pela própria Vercel.</p></div><div className="cards"><article><h2>Consultar cadastro</h2><p>Para quem já participa da igreja conferir e solicitar atualização.</p><img src={qr(consultUrl)} alt="QR Code para consultar cadastro"/><code>{consultUrl}</code><a href={qr(consultUrl)} target="_blank" rel="noreferrer">Abrir QR Code</a></article><article><h2>Novo cadastro</h2><p>Para novos membros preencherem a ficha pelo Integra.</p><img src={qr(integraUrl)} alt="QR Code para novo cadastro"/><code>{integraUrl}</code><a href={qr(integraUrl)} target="_blank" rel="noreferrer">Abrir QR Code</a></article></div><div className="note"><b>Antes de imprimir:</b> conecte o domínio oficial. Assim os QR Codes não precisarão ser refeitos depois.</div></section><style jsx>{`.materials{min-height:100vh;background:#f3f6f7;color:#173746;padding:28px 16px}.materials>section{width:min(960px,100%);margin:auto;background:#fff;border:1px solid #dfe7ea;border-radius:22px;padding:26px;display:grid;gap:22px}.materials header{display:flex;justify-content:space-between;gap:18px}.materials h1{margin:4px 0}.materials p{color:#71838c}.materials small{color:#df6034;font-weight:900;letter-spacing:.12em}.materials a{color:#173746;font-weight:800}.domain,.note{background:#f6f8f9;border-radius:15px;padding:16px}.domain code{display:block;margin-top:8px;font-size:18px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:16px}.cards article{border:1px solid #dfe7ea;border-radius:18px;padding:20px;display:grid;gap:12px;justify-items:center;text-align:center}.cards h2{margin:0}.cards img{width:260px;max-width:100%;height:auto}.cards code{font-size:12px;word-break:break-all;background:#f3f6f7;padding:10px;border-radius:10px}.cards a{background:#df6034;color:#fff;text-decoration:none;padding:11px 15px;border-radius:11px}.note{background:#fff6df;color:#805400}@media(max-width:700px){.materials header{display:grid}.cards{grid-template-columns:1fr}}`}</style></main>}
