-- Central de automações da CEAMI e plano de leitura bíblica 2026.
-- Execute esta migration antes de publicar os arquivos da aba /automacoes.

create extension if not exists "pgcrypto";
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.automations (
  id text primary key,
  name text not null check (char_length(name) between 3 and 80),
  type text not null check (type in ('birthday', 'reading_plan', 'custom')),
  enabled boolean not null default false,
  send_time time not null default '08:00:00',
  timezone text not null default 'America/Sao_Paulo',
  group_id text not null check (group_id ~ '^[0-9]+@g\.us$'),
  message_template text not null check (char_length(message_template) between 1 and 4000),
  config jsonb not null default '{}'::jsonb,
  last_sent_date date,
  last_sent_at timestamptz,
  last_status text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_plan_entries (
  id bigint generated by default as identity primary key,
  reading_date date not null unique,
  reference text not null check (char_length(reference) between 2 and 180),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.automation_runs (
  id uuid primary key default gen_random_uuid(),
  automation_id text not null references public.automations(id) on delete cascade,
  idempotency_key text not null unique,
  run_type text not null check (run_type in ('automatic', 'manual')),
  scheduled_date date not null,
  destination_group_id text not null,
  status text not null check (status in ('processing', 'queued', 'skipped', 'failed')),
  message text,
  metadata jsonb not null default '{}'::jsonb,
  provider_message_id text,
  provider_status text,
  provider_response jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists automations_enabled_time_idx
  on public.automations (enabled, send_time);
create index if not exists automation_runs_automation_created_idx
  on public.automation_runs (automation_id, created_at desc);
create index if not exists reading_plan_entries_date_idx
  on public.reading_plan_entries (reading_date);

insert into public.automations (
  id, name, type, enabled, send_time, timezone, group_id, message_template, config,
  last_sent_date, last_sent_at, last_status, last_error
)
select
  'birthdays',
  'Aniversários',
  'birthday',
  coalesce(settings.enabled, true),
  coalesce(settings.send_time, '08:30:00'::time),
  coalesce(nullif(settings.timezone, ''), 'America/Sao_Paulo'),
  coalesce(nullif(settings.group_id, ''), '120363148206200208@g.us'),
  E'🎉 *Hoje é dia de celebrar!*\n\nA CEAMI deseja um feliz aniversário para:\n\n{{aniversariantes}}\n\nQue Deus continue abençoando cada vida, família e caminhada. Que este novo ciclo seja cheio da presença de Deus, alegria e propósito.\n\nDeixe aqui sua mensagem de carinho! 🧡',
  '{}'::jsonb,
  settings.last_sent_date,
  settings.last_sent_at,
  settings.last_status,
  settings.last_error
from (select 1) source
left join public.birthday_automation_settings settings on settings.id = 'default'
on conflict (id) do update set
  group_id = excluded.group_id,
  timezone = excluded.timezone,
  updated_at = now();

insert into public.automations (
  id, name, type, enabled, send_time, timezone, group_id, message_template, config
)
select
  'reading-plan',
  'Plano de leitura',
  'reading_plan',
  false,
  '07:00:00',
  'America/Sao_Paulo',
  coalesce(
    (select nullif(group_id, '') from public.automations where id = 'birthdays'),
    '120363148206200208@g.us'
  ),
  E'📖 *Plano de Leitura CEAMI*\n\nBom dia, igreja! 🙏\n\nA leitura de hoje, {{data}}, é:\n\n📚 *{{leitura}}*\n\nSepare um momento do seu dia para estar na presença de Deus e meditar na Palavra.\n\nDeus abençoe sua leitura! ❤️',
  '{"planYear": 2026}'::jsonb
on conflict (id) do nothing;

insert into public.reading_plan_entries (reading_date, reference)
values
  ('2026-01-01', 'Gênesis 1 a 3'),
  ('2026-01-02', 'Gênesis 4 a 6'),
  ('2026-01-03', 'Gênesis 7 a 9'),
  ('2026-01-04', 'Gênesis 10 a 11'),
  ('2026-01-05', 'Jó 1 a 4'),
  ('2026-01-06', 'Jó 5 a 7'),
  ('2026-01-07', 'Jó 8 a 10'),
  ('2026-01-08', 'Jó 11 a 13'),
  ('2026-01-09', 'Jó 14 a 17'),
  ('2026-01-10', 'Jó 18 a 20'),
  ('2026-01-11', 'Jó 21 a 24'),
  ('2026-01-12', 'Jó 25 a 27'),
  ('2026-01-13', 'Jó 28 a 31'),
  ('2026-01-14', 'Jó 32 a 34'),
  ('2026-01-15', 'Jó 35 a 38'),
  ('2026-01-16', 'Jó 39 a 42'),
  ('2026-01-17', 'Gênesis 12 a 15'),
  ('2026-01-18', 'Gênesis 16 a 19'),
  ('2026-01-19', 'Gênesis 20 a 22'),
  ('2026-01-20', 'Gênesis 23 a 26'),
  ('2026-01-21', 'Gênesis 27 a 29'),
  ('2026-01-22', 'Gênesis 30 a 32'),
  ('2026-01-23', 'Gênesis 33 a 36'),
  ('2026-01-24', 'Gênesis 37 a 39'),
  ('2026-01-25', 'Gênesis 40 a 42'),
  ('2026-01-26', 'Gênesis 43 a 46'),
  ('2026-01-27', 'Gênesis 47 a 50'),
  ('2026-01-28', 'Êxodo 1 a 4'),
  ('2026-01-29', 'Êxodo 5 a 7'),
  ('2026-01-30', 'Êxodo 8 a 10'),
  ('2026-01-31', 'Êxodo 11 a 13'),
  ('2026-02-01', 'Êxodo 14 a 17'),
  ('2026-02-02', 'Êxodo 18 a 20'),
  ('2026-02-03', 'Êxodo 21 a 24'),
  ('2026-02-04', 'Êxodo 25 a 27'),
  ('2026-02-05', 'Êxodo 28 a 31'),
  ('2026-02-06', 'Êxodo 32 a 34'),
  ('2026-02-07', 'Êxodo 35 a 37'),
  ('2026-02-08', 'Êxodo 38 a 40'),
  ('2026-02-09', 'Levítico 1 a 4'),
  ('2026-02-10', 'Levítico 5 a 7'),
  ('2026-02-11', 'Levítico 8 a 10'),
  ('2026-02-12', 'Levítico 11 a 13'),
  ('2026-02-13', 'Levítico 14 a 16'),
  ('2026-02-14', 'Levítico 17 a 19'),
  ('2026-02-15', 'Levítico 20 a 23'),
  ('2026-02-16', 'Levítico 24 a 27'),
  ('2026-02-17', 'Números 1 a 3'),
  ('2026-02-18', 'Números 4 a 6'),
  ('2026-02-19', 'Números 7 a 10'),
  ('2026-02-20', 'Números 11 a 14'),
  ('2026-02-21', 'Números 15 a 17'),
  ('2026-02-22', 'Números 18 a 20'),
  ('2026-02-23', 'Números 21 a 24'),
  ('2026-02-24', 'Números 25 a 27'),
  ('2026-02-25', 'Números 28 a 30'),
  ('2026-02-26', 'Números 31 a 33'),
  ('2026-02-27', 'Números 34 a 36'),
  ('2026-02-28', 'Deuteronômio 1 a 3'),
  ('2026-03-01', 'Deuteronômio 4 a 6'),
  ('2026-03-02', 'Deuteronômio 7 a 9'),
  ('2026-03-03', 'Deuteronômio 10 a 12'),
  ('2026-03-04', 'Deuteronômio 13 a 16'),
  ('2026-03-05', 'Deuteronômio 17 a 19'),
  ('2026-03-06', 'Deuteronômio 20 a 22'),
  ('2026-03-07', 'Deuteronômio 23 a 25'),
  ('2026-03-08', 'Deuteronômio 26 a 28'),
  ('2026-03-09', 'Deuteronômio 29 a 31'),
  ('2026-03-10', 'Deuteronômio 32 a 34'),
  ('2026-03-11', 'Josué 1 a 4'),
  ('2026-03-12', 'Josué 5 a 7'),
  ('2026-03-13', 'Josué 8 a 11'),
  ('2026-03-14', 'Josué 12 a 15'),
  ('2026-03-15', 'Josué 16 a 18'),
  ('2026-03-16', 'Josué 19 a 21'),
  ('2026-03-17', 'Josué 22 a 24'),
  ('2026-03-18', 'Juízes 1 a 4'),
  ('2026-03-19', 'Juízes 5 a 8'),
  ('2026-03-20', 'Juízes 9 a 12'),
  ('2026-03-21', 'Juízes 13 a 15'),
  ('2026-03-22', 'Juízes 16 a 18'),
  ('2026-03-23', 'Juízes 19 a 21'),
  ('2026-03-24', 'Rute 1 a 4'),
  ('2026-03-25', '1 Samuel 1 a 3'),
  ('2026-03-26', '1 Samuel 4 a 7'),
  ('2026-03-27', '1 Samuel 8 a 10'),
  ('2026-03-28', '1 Samuel 11 a 13'),
  ('2026-03-29', '1 Samuel 14 a 16'),
  ('2026-03-30', '1 Samuel 17 a 20'),
  ('2026-03-31', '1 Samuel 21 a 24'),
  ('2026-04-01', '1 Samuel 25 a 28'),
  ('2026-04-02', '1 Samuel 29 a 31'),
  ('2026-04-03', '2 Samuel 1 a 4'),
  ('2026-04-04', '2 Samuel 5 a 8'),
  ('2026-04-05', '2 Samuel 9 a 12'),
  ('2026-04-06', '2 Samuel 13 a 15'),
  ('2026-04-07', '2 Samuel 16 a 18'),
  ('2026-04-08', '2 Samuel 19 a 21'),
  ('2026-04-09', '2 Samuel 22 a 24'),
  ('2026-04-10', 'Salmos 1 a 3'),
  ('2026-04-11', 'Salmos 4 a 6'),
  ('2026-04-12', 'Salmos 7 a 9'),
  ('2026-04-13', 'Salmos 10 a 12'),
  ('2026-04-14', 'Salmos 13 a 15'),
  ('2026-04-15', 'Salmos 16 a 18'),
  ('2026-04-16', 'Salmos 19 a 21'),
  ('2026-04-17', 'Salmos 22 a 24'),
  ('2026-04-18', 'Salmos 25 a 27'),
  ('2026-04-19', 'Salmos 28 a 30'),
  ('2026-04-20', 'Salmos 31 a 33'),
  ('2026-04-21', 'Salmos 34 a 36'),
  ('2026-04-22', 'Salmos 37 a 39'),
  ('2026-04-23', 'Salmos 40 a 42'),
  ('2026-04-24', 'Salmos 43 a 45'),
  ('2026-04-25', 'Salmos 46 a 48'),
  ('2026-04-26', 'Salmos 49 a 51'),
  ('2026-04-27', 'Salmos 52 a 54'),
  ('2026-04-28', 'Salmos 55 a 57'),
  ('2026-04-29', 'Salmos 58 a 60'),
  ('2026-04-30', 'Salmos 61 a 63'),
  ('2026-05-01', 'Salmos 64 a 66'),
  ('2026-05-02', 'Salmos 67 a 69'),
  ('2026-05-03', 'Salmos 70 a 72'),
  ('2026-05-04', 'Salmos 73 a 75'),
  ('2026-05-05', 'Salmos 76 a 78'),
  ('2026-05-06', 'Salmos 79 a 81'),
  ('2026-05-07', 'Salmos 82 a 84'),
  ('2026-05-08', 'Salmos 85 a 87'),
  ('2026-05-09', 'Salmos 88 a 90'),
  ('2026-05-10', 'Salmos 91 a 93'),
  ('2026-05-11', 'Salmos 94 a 96'),
  ('2026-05-12', 'Salmos 97 a 99'),
  ('2026-05-13', 'Salmos 100 a 102'),
  ('2026-05-14', 'Salmos 103 a 105'),
  ('2026-05-15', 'Salmos 106 a 108'),
  ('2026-05-16', 'Salmos 109 a 111'),
  ('2026-05-17', 'Salmos 112 a 114'),
  ('2026-05-18', 'Salmos 115 a 118'),
  ('2026-05-19', 'Salmos 119'),
  ('2026-05-20', 'Salmos 120 a 123'),
  ('2026-05-21', 'Salmos 124 a 126'),
  ('2026-05-22', 'Salmos 127 a 129'),
  ('2026-05-23', 'Salmos 130 a 132'),
  ('2026-05-24', 'Salmos 133 a 135'),
  ('2026-05-25', 'Salmos 136 a 138'),
  ('2026-05-26', 'Salmos 139 a 141'),
  ('2026-05-27', 'Salmos 142 a 144'),
  ('2026-05-28', 'Salmos 145 a 147'),
  ('2026-05-29', 'Salmos 148 a 150'),
  ('2026-05-30', '1 Reis 1 a 4'),
  ('2026-05-31', 'Provérbios 1 a 3'),
  ('2026-06-01', 'Provérbios 4 a 7'),
  ('2026-06-02', 'Provérbios 8 a 11'),
  ('2026-06-03', 'Provérbios 12 a 14'),
  ('2026-06-04', 'Provérbios 15 a 18'),
  ('2026-06-05', 'Provérbios 19 a 21'),
  ('2026-06-06', 'Provérbios 22 a 24'),
  ('2026-06-07', 'Provérbios 25 a 28'),
  ('2026-06-08', 'Provérbios 29 a 31'),
  ('2026-06-09', 'Eclesiastes 1 a 3'),
  ('2026-06-10', 'Eclesiastes 4 a 6'),
  ('2026-06-11', 'Eclesiastes 7 a 9'),
  ('2026-06-12', 'Eclesiastes 10 a 12'),
  ('2026-06-13', 'Cânticos 1 a 4'),
  ('2026-06-14', 'Cânticos 5 a 8'),
  ('2026-06-15', '1 Reis 5 a 7'),
  ('2026-06-16', '1 Reis 8 a 10'),
  ('2026-06-17', '1 Reis 11 a 13'),
  ('2026-06-18', '1 Reis 14 a 16'),
  ('2026-06-19', '1 Reis 17 a 19'),
  ('2026-06-20', '1 Reis 20 a 22'),
  ('2026-06-21', '2 Reis 1 a 3'),
  ('2026-06-22', '2 Reis 4 a 6'),
  ('2026-06-23', '2 Reis 7 a 10'),
  ('2026-06-24', '2 Reis 11 a 13'),
  ('2026-06-25', 'Joel 1 a 3'),
  ('2026-06-26', '2 Reis 14; Jonas 1 a 4'),
  ('2026-06-27', 'Amós 1 a 3'),
  ('2026-06-28', 'Amós 4 a 6'),
  ('2026-06-29', 'Amós 7 a 9'),
  ('2026-06-30', '2 Reis 15 a 17'),
  ('2026-07-01', 'Oséias 1 a 4'),
  ('2026-07-02', 'Oséias 5 a 7'),
  ('2026-07-03', 'Oséias 8 a 10'),
  ('2026-07-04', 'Oséias 11 a 14'),
  ('2026-07-05', '2 Reis 18 a 19'),
  ('2026-07-06', 'Isaías 1 a 3'),
  ('2026-07-07', 'Isaías 4 a 6'),
  ('2026-07-08', 'Isaías 7 a 9'),
  ('2026-07-09', 'Isaías 10 a 12'),
  ('2026-07-10', 'Isaías 13 a 15'),
  ('2026-07-11', 'Isaías 16 a 18'),
  ('2026-07-12', 'Isaías 19 a 21'),
  ('2026-07-13', 'Isaías 22 a 24'),
  ('2026-07-14', 'Isaías 25 a 27'),
  ('2026-07-15', 'Isaías 28 a 30'),
  ('2026-07-16', 'Isaías 31 a 33'),
  ('2026-07-17', 'Isaías 34 a 36'),
  ('2026-07-18', 'Isaías 37 a 39; 2 Reis 20'),
  ('2026-07-19', 'Isaías 40 a 42'),
  ('2026-07-20', 'Isaías 43 a 45'),
  ('2026-07-21', 'Isaías 46 a 48'),
  ('2026-07-22', 'Isaías 49 a 51'),
  ('2026-07-23', 'Isaías 52 a 54'),
  ('2026-07-24', 'Isaías 55 a 57'),
  ('2026-07-25', 'Isaías 58 a 60'),
  ('2026-07-26', 'Isaías 61 a 63'),
  ('2026-07-27', 'Isaías 64 a 66'),
  ('2026-07-28', 'Miquéias 1 a 4'),
  ('2026-07-29', 'Miquéias 5 a 7'),
  ('2026-07-30', 'Naum 1 a 3'),
  ('2026-07-31', 'Sofonias 1 a 3'),
  ('2026-08-01', 'Habacuque 1 a 3'),
  ('2026-08-02', 'Obadias 1; Jeremias 1'),
  ('2026-08-03', 'Jeremias 2 a 5'),
  ('2026-08-04', 'Jeremias 6 a 8'),
  ('2026-08-05', 'Jeremias 9 a 12'),
  ('2026-08-06', 'Jeremias 13 a 16'),
  ('2026-08-07', 'Jeremias 17 a 20'),
  ('2026-08-08', 'Jeremias 21 a 23'),
  ('2026-08-09', 'Jeremias 24 a 26'),
  ('2026-08-10', 'Jeremias 27 a 29'),
  ('2026-08-11', 'Jeremias 30 a 32'),
  ('2026-08-12', 'Jeremias 33 a 37'),
  ('2026-08-13', '2 Reis 25'),
  ('2026-08-14', 'Jeremias 38 a 42'),
  ('2026-08-15', 'Jeremias 43 a 46'),
  ('2026-08-16', 'Jeremias 47 a 49'),
  ('2026-08-17', 'Jeremias 50 a 52'),
  ('2026-08-18', 'Lamentações 1 a 5'),
  ('2026-08-19', '1 Crônicas 1 a 3'),
  ('2026-08-20', '1 Crônicas 4 a 6'),
  ('2026-08-21', '1 Crônicas 7 a 9'),
  ('2026-08-22', '1 Crônicas 10 a 13'),
  ('2026-08-23', '1 Crônicas 14 a 16'),
  ('2026-08-24', '1 Crônicas 17 a 19'),
  ('2026-08-25', '1 Crônicas 20 a 23'),
  ('2026-08-26', '1 Crônicas 24 a 26'),
  ('2026-08-27', '1 Crônicas 27 a 29'),
  ('2026-08-28', '2 Crônicas 1 a 3'),
  ('2026-08-29', '2 Crônicas 4 a 6'),
  ('2026-08-30', '2 Crônicas 7 a 9'),
  ('2026-08-31', '2 Crônicas 10 a 13'),
  ('2026-09-01', '2 Crônicas 14 a 16'),
  ('2026-09-02', '2 Crônicas 17 a 19'),
  ('2026-09-03', '2 Crônicas 20 a 22'),
  ('2026-09-04', '2 Crônicas 23 a 25'),
  ('2026-09-05', '2 Crônicas 26 a 29'),
  ('2026-09-06', '2 Crônicas 30 a 33'),
  ('2026-09-07', '2 Crônicas 34 a 36'),
  ('2026-09-08', '2 Reis 21 a 24'),
  ('2026-09-09', 'Ezequiel 1 a 4'),
  ('2026-09-10', 'Ezequiel 5 a 8'),
  ('2026-09-11', 'Ezequiel 9 a 12'),
  ('2026-09-12', 'Ezequiel 13 a 16'),
  ('2026-09-13', 'Ezequiel 17 a 20'),
  ('2026-09-14', 'Ezequiel 21 a 24'),
  ('2026-09-15', 'Ezequiel 25 a 27'),
  ('2026-09-16', 'Ezequiel 28 a 30'),
  ('2026-09-17', 'Ezequiel 31 a 33'),
  ('2026-09-18', 'Ezequiel 34 a 36'),
  ('2026-09-19', 'Ezequiel 37 a 39'),
  ('2026-09-20', 'Ezequiel 40 a 42'),
  ('2026-09-21', 'Ezequiel 43 a 45'),
  ('2026-09-22', 'Ezequiel 46 a 48'),
  ('2026-09-23', 'Daniel 1 a 3'),
  ('2026-09-24', 'Daniel 4 a 6'),
  ('2026-09-25', 'Daniel 7 a 9'),
  ('2026-09-26', 'Daniel 10 a 12'),
  ('2026-09-27', 'Ester 1 a 3'),
  ('2026-09-28', 'Ester 4 a 7'),
  ('2026-09-29', 'Ester 8 a 10'),
  ('2026-09-30', 'Esdras 1 a 4'),
  ('2026-10-01', 'Ageu 1 e 2; Zacarias 1'),
  ('2026-10-02', 'Zacarias 2 a 5'),
  ('2026-10-03', 'Zacarias 6 a 10'),
  ('2026-10-04', 'Zacarias 11 a 14'),
  ('2026-10-05', 'Esdras 5 a 7'),
  ('2026-10-06', 'Esdras 8 a 10'),
  ('2026-10-07', 'Neemias 1 a 3'),
  ('2026-10-08', 'Neemias 4 a 6'),
  ('2026-10-09', 'Neemias 7 a 9'),
  ('2026-10-10', 'Neemias 10 a 13'),
  ('2026-10-11', 'Malaquias 1 a 4'),
  ('2026-10-12', 'Mateus 1 a 4'),
  ('2026-10-13', 'Mateus 5 a 7'),
  ('2026-10-14', 'Mateus 8 a 11'),
  ('2026-10-15', 'Mateus 12 a 15'),
  ('2026-10-16', 'Mateus 16 a 19'),
  ('2026-10-17', 'Mateus 20 a 22'),
  ('2026-10-18', 'Mateus 23 a 25'),
  ('2026-10-19', 'Mateus 26 a 28'),
  ('2026-10-20', 'Marcos 1 a 3'),
  ('2026-10-21', 'Marcos 4 a 6'),
  ('2026-10-22', 'Marcos 7 a 10'),
  ('2026-10-23', 'Marcos 11 a 13'),
  ('2026-10-24', 'Marcos 14 a 16'),
  ('2026-10-25', 'Lucas 1 a 3'),
  ('2026-10-26', 'Lucas 4 a 6'),
  ('2026-10-27', 'Lucas 7 a 9'),
  ('2026-10-28', 'Lucas 10 a 13'),
  ('2026-10-29', 'Lucas 14 a 17'),
  ('2026-10-30', 'Lucas 18 a 21'),
  ('2026-10-31', 'Lucas 22 a 24'),
  ('2026-11-01', 'João 1 a 3'),
  ('2026-11-02', 'João 4 a 6'),
  ('2026-11-03', 'João 7 a 10'),
  ('2026-11-04', 'João 11 a 13'),
  ('2026-11-05', 'João 14 a 17'),
  ('2026-11-06', 'João 18 a 21'),
  ('2026-11-07', 'Atos 1 a 3'),
  ('2026-11-08', 'Atos 4 a 6'),
  ('2026-11-09', 'Atos 7 a 9'),
  ('2026-11-10', 'Atos 10 a 13'),
  ('2026-11-11', 'Tiago 1 e 2'),
  ('2026-11-12', 'Tiago 3 a 5'),
  ('2026-11-13', 'Atos 14; Gálatas 1 a 3'),
  ('2026-11-14', 'Gálatas 4 a 6'),
  ('2026-11-15', 'Atos 15 a 19'),
  ('2026-11-16', '1 Tessalonicenses 1 a 5'),
  ('2026-11-17', '2 Tessalonicenses 1 a 3'),
  ('2026-11-18', '1 Coríntios 1 a 4'),
  ('2026-11-19', '1 Coríntios 5 a 8'),
  ('2026-11-20', '1 Coríntios 9 a 12'),
  ('2026-11-21', '1 Coríntios 13 a 16'),
  ('2026-11-22', '2 Coríntios 1 a 3'),
  ('2026-11-23', '2 Coríntios 4 a 6'),
  ('2026-11-24', '2 Coríntios 7 a 9'),
  ('2026-11-25', '2 Coríntios 10 a 13'),
  ('2026-11-26', 'Romanos 1 a 4'),
  ('2026-11-27', 'Romanos 5 a 8'),
  ('2026-11-28', 'Romanos 9 a 11'),
  ('2026-11-29', 'Romanos 12 a 16'),
  ('2026-11-30', 'Atos 20 a 22'),
  ('2026-12-01', 'Atos 23 a 25'),
  ('2026-12-02', 'Atos 26 a 28'),
  ('2026-12-03', 'Efésios 1 a 3'),
  ('2026-12-04', 'Efésios 4 a 6'),
  ('2026-12-05', 'Filipenses 1 a 4'),
  ('2026-12-06', 'Colossenses 1 a 4'),
  ('2026-12-07', 'Hebreus 1 a 4'),
  ('2026-12-08', 'Hebreus 5 a 7'),
  ('2026-12-09', 'Hebreus 8 a 10'),
  ('2026-12-10', 'Hebreus 11 a 13'),
  ('2026-12-11', 'Filemom 1'),
  ('2026-12-12', '1 Pedro 1 e 2'),
  ('2026-12-13', '1 Pedro 3 a 5'),
  ('2026-12-14', '2 Pedro 1 a 3'),
  ('2026-12-15', '1 Timóteo 1 a 3'),
  ('2026-12-16', '1 Timóteo 4 a 6'),
  ('2026-12-17', 'Tito 1 a 3'),
  ('2026-12-18', '2 Timóteo 1 a 4'),
  ('2026-12-19', '1 João 1 e 2'),
  ('2026-12-20', '1 João 3 a 5'),
  ('2026-12-21', '2 João 1'),
  ('2026-12-22', '3 João 1'),
  ('2026-12-23', 'Judas 1'),
  ('2026-12-24', 'Apocalipse 1 a 3'),
  ('2026-12-25', 'Apocalipse 4 a 6'),
  ('2026-12-26', 'Apocalipse 7 a 9'),
  ('2026-12-27', 'Apocalipse 10 a 12'),
  ('2026-12-28', 'Apocalipse 13 a 15'),
  ('2026-12-29', 'Apocalipse 16 a 18'),
  ('2026-12-30', 'Apocalipse 19 a 21'),
  ('2026-12-31', 'Apocalipse 22')
on conflict (reading_date) do update set
  reference = excluded.reference,
  updated_at = now();

alter table public.automations enable row level security;
alter table public.reading_plan_entries enable row level security;
alter table public.automation_runs enable row level security;

drop policy if exists automations_admin_all on public.automations;
create policy automations_admin_all
on public.automations for all to authenticated
using (public.is_ceami_admin())
with check (public.is_ceami_admin());

drop policy if exists reading_plan_admin_all on public.reading_plan_entries;
create policy reading_plan_admin_all
on public.reading_plan_entries for all to authenticated
using (public.is_ceami_admin())
with check (public.is_ceami_admin());

drop policy if exists automation_runs_admin_select on public.automation_runs;
create policy automation_runs_admin_select
on public.automation_runs for select to authenticated
using (public.is_ceami_admin());

revoke all on public.automations from anon;
revoke all on public.reading_plan_entries from anon;
revoke all on public.automation_runs from anon;
grant select, insert, update, delete on public.automations to authenticated;
grant select, insert, update, delete on public.reading_plan_entries to authenticated;
grant select on public.automation_runs to authenticated;
grant all on public.automations to service_role;
grant all on public.reading_plan_entries to service_role;
grant all on public.automation_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.api_security_secrets (name, secret)
values ('birthday_cron', encode(gen_random_bytes(32), 'hex'))
on conflict (name) do nothing;

do $$
declare
  v_job_id bigint;
  v_secret text;
  v_command text;
begin
  if to_regclass('cron.job') is null then
    return;
  end if;

  select jobid into v_job_id from cron.job where jobname = 'ceami-birthday-automation';
  if v_job_id is not null then perform cron.unschedule(v_job_id); end if;

  select jobid into v_job_id from cron.job where jobname = 'ceami-automations';
  if v_job_id is not null then perform cron.unschedule(v_job_id); end if;

  select secret into v_secret
  from public.api_security_secrets
  where name = 'birthday_cron';

  v_command := format(
    $cmd$
      select net.http_post(
        url := 'https://ceami-membros.vercel.app/api/automations/automatic',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer %s'
        ),
        body := '{}'::jsonb,
        timeout_milliseconds := 50000
      );
    $cmd$,
    v_secret
  );

  perform cron.schedule('ceami-automations', '* * * * *', v_command);
end;
$$;

notify pgrst, 'reload schema';
