import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUiRole } from '@/lib/server/current-profile';
import { evolutionConfigured, getEvolutionConfig } from '@/lib/server/evolution';
import { consumeRateLimit, getServiceClient, requestComesFromSameSite } from '@/lib/server/security';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
const SEMINAR_SLUG = 'seminario-apocalipse-2026';
type Candidate = { id:string; name:string; originalPhone:string; normalizedPhone:string; status:'confirmed'|'warning'|'invalid'; reason:string; whatsappExists:boolean|null; material:'PDF'|'Física' };
function text(v:unknown){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function material(v:unknown):'PDF'|'Física'|''{const s=text(v);if(s.includes('pdf')||s.includes('digital'))return 'PDF';if(s.includes('fisic'))return 'Física';return ''}
function paymentStatus(a:Record<string,unknown>){const p=a.__payment;return p&&typeof p==='object'&&!Array.isArray(p)?String((p as Record<string,unknown>).status||''):''}
function alreadyDelivered(a:Record<string,unknown>){const d=a.__seminar_pdf_delivery;return !!d&&typeof d==='object'&&!Array.isArray(d)&&String((d as Record<string,unknown>).status||'')==='sent'}
function normalizePhone(v:unknown){let d=String(v??'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('0')&&d.length>11)d=d.replace(/^0+/,'');if(d.length===10||d.length===11)d=`55${d}`;return d}
function validatePhone(v:unknown){const original=String(v??'').trim();const d=normalizePhone(original);if(!original)return{original,normalized:'',status:'invalid' as const,reason:'Telefone não informado.'};if(!d.startsWith('55'))return{original,normalized:d,status:'invalid' as const,reason:'Número não está no padrão brasileiro (+55).'};const n=d.slice(2);if(n.length!==10&&n.length!==11)return{original,normalized:d,status:'invalid' as const,reason:'Quantidade de dígitos inválida.'};const ddd=Number(n.slice(0,2));if(!Number.isInteger(ddd)||ddd<11||ddd>99||n[0]==='0'||n[1]==='0')return{original,normalized:d,status:'invalid' as const,reason:'DDD inválido.'};const local=n.slice(2);if(/^(\d)\1+$/.test(local))return{original,normalized:d,status:'invalid' as const,reason:'Número local inválido.'};if(n.length===10)return{original,normalized:d,status:'warning' as const,reason:'Número com 8 dígitos locais. Revisar se deveria possuir o 9º dígito.'};if(local[0]!=='9')return{original,normalized:d,status:'warning' as const,reason:'Número móvel de 9 dígitos não começa com 9. Revisar antes do envio.'};return{original,normalized:d,status:'confirmed' as const,reason:'Formato brasileiro válido.'}}
function providerResults(payload:unknown){const root=payload as Record<string,unknown>|null;const rows=Array.isArray(payload)?payload:Array.isArray(root?.data)?root!.data:Array.isArray(root?.response)?root!.response:[];const map=new Map<string,boolean>();for(const item of rows as unknown[]){if(!item||typeof item!=='object')continue;const r=item as Record<string,unknown>;const n=normalizePhone(r.number||r.jid||r.remoteJid||'');if(!n)continue;const exists=r.exists===true||r.exists==='true'||r.isWhatsapp===true||r.registered===true;map.set(n,exists);if(n.length===12)map.set(`${n.slice(0,4)}9${n.slice(4)}`,exists);if(n.length===13&&n.charAt(4)==='9')map.set(`${n.slice(0,4)}${n.slice(5)}`,exists)}return map}
async function verify(numbers:string[]){const c=getEvolutionConfig();if(!evolutionConfigured(c)||!numbers.length)return null;try{const r=await fetch(`${c.apiUrl}/chat/whatsappNumbers/${encodeURIComponent(c.instance)}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:c.apiKey},body:JSON.stringify({numbers}),cache:'no-store',signal:AbortSignal.timeout(12000)});return r.ok?providerResults(await r.json()):null}catch{return null}}

export async function GET(request:NextRequest){if(!requestComesFromSameSite(request))return NextResponse.json({error:'Origem da solicitação não autorizada.'},{status:403});if(await getCurrentUiRole()!=='admin')return NextResponse.json({error:'Acesso restrito ao administrador.'},{status:403});if(!await consumeRateLimit(request,'seminar_pdf_preflight',60,6))return NextResponse.json({error:'Aguarde um minuto antes de conferir novamente.'},{status:429});const service=getServiceClient();if(!service)return NextResponse.json({error:'Serviço temporariamente indisponível.'},{status:503});const{data:form}=await service.from('forms').select('id').eq('slug',SEMINAR_SLUG).maybeSingle();if(!form)return NextResponse.json({error:'Formulário do seminário não encontrado.'},{status:404});const{data,error}=await service.from('form_submissions').select('id, respondent_name, respondent_phone, answers, created_at').eq('form_id',form.id).order('created_at',{ascending:true});if(error)return NextResponse.json({error:'Não foi possível carregar as inscrições.'},{status:500});
 const candidates:Candidate[]=[];let alreadySent=0;for(const row of data||[]){const a=row.answers&&typeof row.answers==='object'&&!Array.isArray(row.answers)?row.answers as Record<string,unknown>:{};const m=material(a.apostila);if(paymentStatus(a)!=='paid'||!m)continue;if(alreadyDelivered(a)){alreadySent++;continue}const phone=row.respondent_phone||a.telefone||a.whatsapp||a.celular||'';const check=validatePhone(phone);candidates.push({id:row.id,name:String(row.respondent_name||a.nome_completo||'Não informado'),originalPhone:check.original,normalizedPhone:check.normalized,status:check.status,reason:check.reason,whatsappExists:null,material:m})}
 const provider=await verify([...new Set(candidates.filter(x=>x.normalizedPhone).map(x=>x.normalizedPhone))]);for(const item of candidates){if(!provider||!item.normalizedPhone||item.status==='invalid')continue;const exists=provider.get(item.normalizedPhone);if(exists===undefined)continue;item.whatsappExists=exists;if(!exists){item.status='invalid';item.reason='WhatsApp não confirmou este número como cadastrado.'}else if(item.status==='confirmed')item.reason='Formato válido e número confirmado no WhatsApp.'}
 const summary={total:candidates.length,alreadySent,confirmed:candidates.filter(x=>x.status==='confirmed').length,warnings:candidates.filter(x=>x.status==='warning').length,invalid:candidates.filter(x=>x.status==='invalid').length,whatsappChecked:Boolean(provider),readyForBulk:candidates.length>0&&candidates.every(x=>x.status==='confirmed')};return NextResponse.json({ok:true,summary,recipients:candidates},{headers:{'Cache-Control':'no-store'}})}
